### ISSUE TITLE
still working?

### ISSUE THREAD

**Issue by titaniumbones** [schikulski/sage-foundation#1]
just wanted to ask whether you're still using this method, and if it works with recent versions of roots. Thank you!

**Comment by schikulski** [comment]
Hi! No, sorry. I've switched over to Bootstrap a year ago, so I'm afraid this won't work for the current versions.

**Comment by schikulski** [comment]
BTW: In the new Roots 9 you can choose between Foundation and Bootstrap when installing the theme

**Comment by titaniumbones** [comment]
thanks for the response though! I still appreciate it.

Simen Schikulski <notifications@github.com> writes:

> Hi! No, sorry. I've switched over to Bootstrap a year ago, so I'm afraid this won't work for the current versions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
